version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static site"
  build:
    commands:
      - echo "Building and preparing files for deployment"
  post_build:
    commands:
      - echo "Deploying files to S3 with appropriate metadata"
      # Set Content-Type for HTML and JavaScript files, and sync all files
      - aws s3 sync . s3://cicd-demo-andre/ --exclude "*" --include "*.html" --content-type "text/html"
      - aws s3 sync . s3://cicd-demo-andre/ --exclude "*" --include "*.js" --content-type "application/javascript"
      - aws s3 sync . s3://cicd-demo-andre/
      - echo "Deployment to S3 completed"
